## 3.2 马尔可夫过程
- 马尔可夫性质：当且仅当某时刻的状态只取决于上一时刻的状态时。
- 采样：给定一个马尔可夫过程，从某个状态出发，根据其状态转移矩阵生成一个状态序列。

## 3.3 马尔科夫奖励过程
- Markov reward process (MRP): <$S, P, r, \gamma$>
  - $S$: 有限状态的集合
  - $P$: 状态转移概率矩阵，$P_{ss'} = P[S_{t+1} = s' | S_t = s]$
  - $r$: 奖励函数，某个状态$s$的奖励$r(s)$为转移到该状态时可以获得的奖励的期望 （终止状态，奖励为0）
  - $\gamma$: 折扣因子，$0 \leq \gamma \leq 1$
- Return $G_t$: 从时间步$t$开始获得的累积折扣奖励
  - $G_t = R_{t} + \gamma R_{t+1} + \gamma^2 R_{t+2} + ... = \sum_{k=0}^{\infty} \gamma^k R_{t+k}$
  - $R_t$: 在时刻$t$获得的奖励
- value function $v(s)$: 在状态$s$下的价值函数，表示从状态$s$出发所能获得的期望回报
  - $v(s) = \mathbb{E}[G_t | S_t = s]$
  - 贝尔曼方程（Bellman equation）：$V(s) = r(s) + \gamma \sum_{s'∈S} P(s'|s)V(s')$
  - 矩阵形式：$V = R + \gamma P V$，其中$V$为价值函数向量，$R$为奖励向量，$P$为状态转移概率矩阵

In [2]:
import numpy as np
np.random.seed(0)
# 定义状态转移概率矩阵P, 列表
P = [
    [0.9, 0.1, 0.0, 0.0, 0.0, 0.0],
    [0.5, 0.0, 0.5, 0.0, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.6, 0.0, 0.4],
    [0.0, 0.0, 0.0, 0.0, 0.3, 0.7],
    [0.0, 0.2, 0.3, 0.5, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.0, 0.0, 1.0],
]
P = np.array(P)

rewards = [-1, -2, -2, 10, 1, 0]  # 定义奖励函数
gamma = 0.5  # 定义折扣因子

# 给定一条序列,计算从某个索引（起始状态）开始到序列最后（终止状态）得到的回报
def compute_return(start_index, chain, gamma):
    G = 0
    for i in reversed(range(start_index, len(chain))):
        G = gamma * G + rewards[chain[i] - 1]
    return G

# 一个状态序列,s1-s2-s3-s6
chain = [1, 2, 3, 6]
start_index = 0
G = compute_return(start_index, chain, gamma)
print("根据本序列计算得到回报为：%s。" % G)

# 根据本序列计算得到回报为：-2.5。

根据本序列计算得到回报为：-2.5。


In [3]:
def compute(P, rewards, gamma, states_num):
    ''' 利用贝尔曼方程的矩阵形式计算解析解,states_num是MRP的状态数 '''
    rewards = np.array(rewards).reshape((-1, 1))  #将rewards写成列向量形式
    value = np.dot(np.linalg.inv(np.eye(states_num, states_num) - gamma * P), rewards)
    return value


V = compute(P, rewards, gamma, 6)
print("MRP中每个状态价值分别为\n", V)

# MRP中每个状态价值分别为
#  [[-2.01950168]
#  [-2.21451846]
#  [ 1.16142785]
#  [10.53809283]
#  [ 3.58728554]
#  [ 0.        ]]

MRP中每个状态价值分别为
 [[-2.01950168]
 [-2.21451846]
 [ 1.16142785]
 [10.53809283]
 [ 3.58728554]
 [ 0.        ]]


## 3.4 马尔可夫决策过程
- 有一外界刺激（**Agent**）共同改变此决策过程,mMarkov decision process (MDP)
- <$S, A, P, r, \gamma$>
  - $S$：状态的集合
  - $A$: 有限动作的集合
  - $P(s'|s,a)$: 状态转移概率函数，$= P[S_{t+1} = s' | S_t = s, A_t = a]$，表示在状态$s$下执行动作$a$后转移到状态$s'$的概率
  - $r(s, a)$: 奖励函数，某个状态$s$下执行动作$a$所获得的奖励的期望
- 策略 $\pi(a|s)$: 在状态$s$下选择动作$a$的概率分布，选择动作的方法
  - 确定性策略：$\pi(s) = a$，每个状态下只输出确定性动作
  - 随机性策略：$\pi(a|s) = P[A_t = a | S_t = s]$，表示在状态$s$下选择动作$a$的概率
- 状态价值函数 $V^{\pi}(s)$: MDP中基于策略$\pi$的状态价值函数，表示从状态$s$出发并按照策略$\pi$所能获得的期望回报
  - $V^{\pi}(s)= \mathbb{E}_{\pi}[G_t | S_t = s]$
- 动作价值函数 $Q^{\pi}(s, a)$: MDP中基于策略$\pi$的动作价值函数，表示在状态$s$下执行动作$a$并按照策略$\pi$所能获得的期望回报
  - $Q^{\pi}(s, a) = \mathbb{E}_{\pi}[G_t | S_t = s, A_t = a]$
  - $Q^{\pi}(s, a) = r(s, a) + \gamma \sum_{s'∈S} P(s'|s, a) V^{\pi}(s')$
  - $V^{\pi}(s) = \sum_{a∈A} \pi(a|s) Q^{\pi}(s, a)$
- 贝尔曼期望方程（Bellman expectation equation）:
  - $V^{\pi}(s) = \sum_{a∈A} \pi(a|s) [r(s, a) + \gamma \sum_{s'∈S} P(s'|s, a) V^{\pi}(s')]$
  - $Q^{\pi}(s, a) = r(s, a) + \gamma \sum_{s'∈S} P(s'|s, a) \sum_{a'∈A} \pi(a'|s') Q^{\pi}(s', a')$

In [4]:
S = ["s1", "s2", "s3", "s4", "s5"]  # 状态集合
A = ["保持s1", "前往s1", "前往s2", "前往s3", "前往s4", "前往s5", "概率前往"]  # 动作集合
# 状态转移函数
P = {
    "s1-保持s1-s1": 1.0,
    "s1-前往s2-s2": 1.0,
    "s2-前往s1-s1": 1.0,
    "s2-前往s3-s3": 1.0,
    "s3-前往s4-s4": 1.0,
    "s3-前往s5-s5": 1.0,
    "s4-前往s5-s5": 1.0,
    "s4-概率前往-s2": 0.2,
    "s4-概率前往-s3": 0.4,
    "s4-概率前往-s4": 0.4,
}
# 奖励函数
R = {
    "s1-保持s1": -1,
    "s1-前往s2": 0,
    "s2-前往s1": -1,
    "s2-前往s3": -2,
    "s3-前往s4": -2,
    "s3-前往s5": 0,
    "s4-前往s5": 10,
    "s4-概率前往": 1,
}
gamma = 0.5  # 折扣因子
MDP = (S, A, P, R, gamma)

# 策略1,随机策略
Pi_1 = {
    "s1-保持s1": 0.5,
    "s1-前往s2": 0.5,
    "s2-前往s1": 0.5,
    "s2-前往s3": 0.5,
    "s3-前往s4": 0.5,
    "s3-前往s5": 0.5,
    "s4-前往s5": 0.5,
    "s4-概率前往": 0.5,
}
# 策略2
Pi_2 = {
    "s1-保持s1": 0.6,
    "s1-前往s2": 0.4,
    "s2-前往s1": 0.3,
    "s2-前往s3": 0.7,
    "s3-前往s4": 0.5,
    "s3-前往s5": 0.5,
    "s4-前往s5": 0.1,
    "s4-概率前往": 0.9,
}


# 把输入的两个字符串通过“-”连接,便于使用上述定义的P、R变量
def join(str1, str2):
    return str1 + '-' + str2

In [5]:
gamma = 0.5
# 转化后的MRP的状态转移矩阵
P_from_mdp_to_mrp = [
    [0.5, 0.5, 0.0, 0.0, 0.0],
    [0.5, 0.0, 0.5, 0.0, 0.0],
    [0.0, 0.0, 0.0, 0.5, 0.5],
    [0.0, 0.1, 0.2, 0.2, 0.5],
    [0.0, 0.0, 0.0, 0.0, 1.0],
]
P_from_mdp_to_mrp = np.array(P_from_mdp_to_mrp)
R_from_mdp_to_mrp = [-0.5, -1.5, -1.0, 5.5, 0]

V = compute(P_from_mdp_to_mrp, R_from_mdp_to_mrp, gamma, 5)
print("MDP中每个状态价值分别为\n", V)

# MDP中每个状态价值分别为
#  [[-1.22555411]
#  [-1.67666232]
#  [ 0.51890482]
#  [ 6.0756193 ]
#  [ 0.        ]]

MDP中每个状态价值分别为
 [[-1.22555411]
 [-1.67666232]
 [ 0.51890482]
 [ 6.0756193 ]
 [ 0.        ]]


## 3.5 蒙特卡洛方法

In [6]:
def sample(MDP, Pi, timestep_max, number):
    ''' 采样函数,策略Pi,限制最长时间步timestep_max,总共采样序列数number '''
    S, A, P, R, gamma = MDP
    episodes = []
    for _ in range(number):
        episode = []
        timestep = 0
        s = S[np.random.randint(4)]  # 随机选择一个除s5以外的状态s作为起点
        # 当前状态为终止状态或者时间步太长时,一次采样结束
        while s != "s5" and timestep <= timestep_max:
            timestep += 1
            rand, temp = np.random.rand(), 0
            # 在状态s下根据策略选择动作
            for a_opt in A:
                temp += Pi.get(join(s, a_opt), 0) # 获取键值
                if temp > rand:
                    a = a_opt
                    r = R.get(join(s, a), 0)
                    break
            rand, temp = np.random.rand(), 0
            # 根据状态转移概率得到下一个状态s_next
            for s_opt in S:
                temp += P.get(join(join(s, a), s_opt), 0)
                if temp > rand:
                    s_next = s_opt
                    break
            episode.append((s, a, r, s_next))  # 把（s,a,r,s_next）元组放入序列中
            s = s_next  # s_next变成当前状态,开始接下来的循环
        episodes.append(episode)
    return episodes


# 采样5次,每个序列最长不超过1000步
episodes = sample(MDP, Pi_1, 20, 5)
print('第一条序列\n', episodes[0])
print('第二条序列\n', episodes[1])
print('第五条序列\n', episodes[4])

# 第一条序列
#  [('s1', '前往s2', 0, 's2'), ('s2', '前往s3', -2, 's3'), ('s3', '前往s5', 0, 's5')]
# 第二条序列
#  [('s4', '概率前往', 1, 's4'), ('s4', '前往s5', 10, 's5')]
# 第五条序列
#  [('s2', '前往s3', -2, 's3'), ('s3', '前往s4', -2, 's4'), ('s4', '前往s5', 10, 's5')]

第一条序列
 [('s1', '前往s2', 0, 's2'), ('s2', '前往s3', -2, 's3'), ('s3', '前往s5', 0, 's5')]
第二条序列
 [('s4', '概率前往', 1, 's4'), ('s4', '前往s5', 10, 's5')]
第五条序列
 [('s2', '前往s3', -2, 's3'), ('s3', '前往s4', -2, 's4'), ('s4', '前往s5', 10, 's5')]


In [7]:
# 对所有采样序列计算所有状态的价值
def MC(episodes, V, N, gamma):
    for episode in episodes:
        G = 0
        for i in range(len(episode) - 1, -1, -1):  #一个序列从后往前计算
            (s, a, r, s_next) = episode[i]
            G = r + gamma * G
            N[s] = N[s] + 1
            V[s] = V[s] + (G - V[s]) / N[s]


timestep_max = 20
# np.random.seed(0) 最开始给了seed
# 采样1000次,可以自行修改
episodes = sample(MDP, Pi_1, timestep_max, 1000)
gamma = 0.5
V = {"s1": 0, "s2": 0, "s3": 0, "s4": 0, "s5": 0}
N = {"s1": 0, "s2": 0, "s3": 0, "s4": 0, "s5": 0}
MC(episodes, V, N, gamma)
print("使用蒙特卡洛方法计算MDP的状态价值为\n", V)

# 使用蒙特卡洛方法计算MDP的状态价值为
#  {'s1': -1.228923788722258, 's2': -1.6955696284402704, 's3': 0.4823809701532294,
# 's4': 5.967514743019431, 's5': 0}

使用蒙特卡洛方法计算MDP的状态价值为
 {'s1': -1.228923788722258, 's2': -1.6955696284402704, 's3': 0.4823809701532294, 's4': 5.967514743019431, 's5': 0}


## 3.6 占用度量
- $P^{\pi}_t(s): $使用策略$\pi$使得Agent在$t$时刻状态为$s$的概率
- 状态访问分布（state visitation distribution）某一策略下，Agent与MDP交互会访问到的状态的分布
  - $v^{\pi}(s) = (1-\gamma)\sum^{\infty}_{t=0}\gamma^tP^{\pi}_t(s)$
  - 状态访问概率性质：$v^{\pi}(s')=(1-\gamma)v_0(s_0=s')+\gamma\int P(s'|s,a)\pi(a|s)v^{\pi}(s)dsda$
- 占用度量 Occupancy Measure: Agent在状态$s$下执行动作$a$的联合分布
  - $\rho^{\pi}(s, a) = \pi(a|s)v^{\pi}(s)$
  - $\rho^{\pi}(s, a)=(1-\gamma)\sum^{\infty}_{t=0}\gamma^tP^{\pi}_t(s)\pi(a|s)$
  - $\rho^{\pi}(s', a') = (1-\gamma)\pi(a'|s')v_0(s_0=s') + \gamma\int P(s'|s,a)\pi(a'|s')\rho^{\pi}(s, a)dsda$

In [8]:
def occupancy(episodes, s, a, timestep_max, gamma):
    ''' 计算状态动作对（s,a）出现的频率,以此来估算策略的占用度量 '''
    rho = 0
    total_times = np.zeros(timestep_max)  # 记录每个时间步t各被经历过几次
    occur_times = np.zeros(timestep_max)  # 记录(s_t,a_t)=(s,a)的次数
    for episode in episodes:
        for i in range(len(episode)):
            (s_opt, a_opt, r, s_next) = episode[i]
            total_times[i] += 1
            if s == s_opt and a == a_opt:
                occur_times[i] += 1
    for i in reversed(range(timestep_max)):
        if total_times[i]:
            rho += gamma**i * occur_times[i] / total_times[i]
    return (1 - gamma) * rho


gamma = 0.5
timestep_max = 1000

episodes_1 = sample(MDP, Pi_1, timestep_max, 1000)
episodes_2 = sample(MDP, Pi_2, timestep_max, 1000)
rho_1 = occupancy(episodes_1, "s4", "概率前往", timestep_max, gamma)
rho_2 = occupancy(episodes_2, "s4", "概率前往", timestep_max, gamma)
print(rho_1, rho_2)

# 0.112567796310472 0.23199480615618912

0.112567796310472 0.23199480615618912
